# Generated by Django 5.2.8 on 2025-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('janr', models.CharField(choices=[('action', 'Action'), ('detectiv', 'Detectiv'), ('drama', 'Drama'), ('animation', 'Animation')])),
                ('yil', models.IntegerField()),
                ('rejissor', models.CharField()),
            ],
        ),
    ]
